name: reusable
on: 
  workflow_call:

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: Use variables
      run: |
        echo "Hello from reusable workflow"
